# Generated by Django 3.2.9 on 2021-11-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amazon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Disney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hulu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Netflix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('director', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('release_year', models.IntegerField()),
                ('rating', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('listed_in', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
