# Generated by Django 3.2.9 on 2021-11-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(error_messages={'unique': '이미 있는 제목입니다.'}, max_length=50, unique=True),
        ),
    ]
